apiVersion: 1
datasources:
  - name: InfluxDB-MASS
    type: influxdb
    access: proxy
    url: http://campus-influxdb:8086
    jsonData:
      version: Flux
      organization: campus-security
      defaultBucket: iot-telemetry
    secureJsonData:
      token: ${INFLUX_TOKEN:-campus-influx-token-changeme}
    isDefault: true

  - name: MongoDB-MASS
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://campus-mongodb:27017
    basicAuth: false
