client localhost {
	ipaddr = 127.0.0.1
	secret = testing123
	require_message_authenticator = true
}

client campus_switch {
	ipaddr = 192.168.0.0/16
	secret = Mass@2026
}

client docker-gw {
	ipaddr = 172.0.0.0/8
	secret = docker
}
